[package]
name = "wrkflw"
version = "0.1.0"
edition = "2021"
description = "GitHub Workflow evaluator for validating workflow files"

[dependencies]
serde = "1.0"
serde_yaml = "0.9"
colored = "2.0"
clap = { version = "4.4", features = ["derive"] }
